package com.finantix.mdl.adbk.core.dto;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContactDTO implements java.io.Serializable {

 
private String type;
static final long serialVersionUID = 1L;
	private String birthDate;
	private String firstName;
	private String gender;
	private Integer id;
	private String lastName;
	private String salutation;
	private String thumbnail;
	private Integer updateVersion;
	private Double altitude;
	private Double latitude;
	private Double longitude;
	private String clientType;
	private String dateBecomeClient;
	private String nationality;
	private Boolean usCitizen;
    public ContactDTO() {
    }

public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	
	public String getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(String birthDate) {
		this.birthDate = birthDate;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getSalutation() {
		return salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	public String getThumbnail() {
		return thumbnail;
	}

	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

	public Integer getUpdateVersion() {
		return updateVersion;
	}

	public void setUpdateVersion(Integer updateVersion) {
		this.updateVersion = updateVersion;
	}

	public Double getAltitude() {
		return altitude;
	}

	public void setAltitude(Double altitude) {
		this.altitude = altitude;
	}

	public Double getLatitude() {
		return latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public String getClientType() {
		return clientType;
	}

	public void setClientType(String clientType) {
		this.clientType = clientType;
	}

	public String getDateBecomeClient() {
		return dateBecomeClient;
	}

	public void setDateBecomeClient(String dateBecomeClient) {
		this.dateBecomeClient = dateBecomeClient;
	}

	public String getNationality() {
		return nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public Boolean getUsCitizen() {
		return usCitizen;
	}

	public void setUsCitizen(Boolean usCitizen) {
		this.usCitizen = usCitizen;
	}

public String toString(){//overriding the toString() method  
  return "ContactDTO: "+lastName+">> "+id;  
 }  


}
