package com.finantix.signer.core.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Signer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean info;

	
	public java.lang.Boolean getInfo() {
		return info;
	}

	public void setInfo(java.lang.Boolean info) {
		this.info = info;
	}

	public java.lang.String getFirstName() {
		return firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.String getPhone() {
		return phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getEmail() {
		return email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	private java.lang.String firstName;


	private java.lang.String lastName;

	
	private java.lang.String phone;

	private java.lang.String email;

	

}