package com.finantix.bp.service.extensions;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Document implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "Type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label(value = "Mandatory")
	private java.lang.String mandatory;
	@org.kie.api.definition.type.Label(value = "WireTransferType")
	private java.lang.String wtType;

	public Document() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getMandatory() {
		return this.mandatory;
	}

	public void setMandatory(java.lang.String mandatory) {
		this.mandatory = mandatory;
	}

	public java.lang.String getWtType() {
		return this.wtType;
	}

	public void setWtType(java.lang.String wtType) {
		this.wtType = wtType;
	}

	public Document(java.lang.String id, java.lang.String type,
			java.lang.String mandatory, java.lang.String wtType) {
		this.id = id;
		this.type = type;
		this.mandatory = mandatory;
		this.wtType = wtType;
	}

}