package com.finantix.mdl.adbk.core.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

//@org.kie.api.definition.type.Description("com.myspace.onboarding.Party")
public class Party implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("domicile")
	private java.lang.String domicile;
	@org.kie.api.definition.type.Label("minor")
	private java.lang.Boolean minor;
	@org.kie.api.definition.type.Label("relation")
	private java.lang.String relation;

	@org.kie.api.definition.type.Label("docs")
	private java.lang.String docs;

	@org.kie.api.definition.type.Label("docList")
	private java.util.List<java.lang.String> docList;

	@org.kie.api.definition.type.Label("idPass")
	private java.lang.Boolean idPass;

	@org.kie.api.definition.type.Label("proof_of_residence")
	private java.lang.Boolean proof_of_residence;

	@org.kie.api.definition.type.Label("birth_cert")
	private java.lang.Boolean birth_cert;

	@org.kie.api.definition.type.Label(value = "actor")
	private java.lang.String actor;
	
	private java.lang.String gender;
	private java.lang.String preferredLanguage;
	private java.lang.Boolean usCitizen;
	public java.lang.String getFirstName() {
		return firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.String getBirthDate() {
		return birthDate;
	}

	public void setBirthDate(java.lang.String birthDate) {
		this.birthDate = birthDate;
	}

	private java.lang.String firstName;
	private java.lang.String lastName;
	
	private java.lang.String birthDate;
	
	
	public java.lang.String getGender() {
		return gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public java.lang.String getPreferredLanguage() {
		return preferredLanguage;
	}

	public void setPreferredLanguage(java.lang.String preferredLanguage) {
		this.preferredLanguage = preferredLanguage;
	}

	public java.lang.Boolean getUsCitizen() {
		return usCitizen;
	}

	public void setUsCitizen(java.lang.Boolean usCitizen) {
		this.usCitizen = usCitizen;
	}


	

	public Party() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDomicile() {
		return this.domicile;
	}

	public void setDomicile(java.lang.String domicile) {
		this.domicile = domicile;
	}

	public java.lang.Boolean getMinor() {
		return this.minor;
	}

	public void setMinor(java.lang.Boolean minor) {
		this.minor = minor;
	}

	public java.lang.String getRelation() {
		return this.relation;
	}

	public void setRelation(java.lang.String relation) {
		this.relation = relation;
	}

	// @Overview
	public String toString() {
		return this.name + ">>" + this.domicile + ">>" + this.minor + ">>"
				+ this.docs + ">>proof_of_residence:" + proof_of_residence
				+ " >>idPass:" + idPass + ">>birth_cert:" + birth_cert +">>this.actor:"+this.actor;
	}

	public java.lang.String getDocs() {
		return this.docs;
	}

	public void setDocs(java.lang.String docs) {
		this.docs = docs;
	}

	public java.util.List<java.lang.String> getDocList() {
		return this.docList;
	}

	public void setDocList(java.util.List<java.lang.String> docList) {
		this.docList = docList;
	}

	public java.lang.Boolean getIdPass() {
		return this.idPass;
	}

	public void setIdPass(java.lang.Boolean idPass) {
		this.idPass = idPass;
	}

	public java.lang.Boolean getProof_of_residence() {
		return this.proof_of_residence;
	}

	public void setProof_of_residence(java.lang.Boolean proof_of_residence) {
		this.proof_of_residence = proof_of_residence;
	}

	public java.lang.Boolean getBirth_cert() {
		return this.birth_cert;
	}

	public void setBirth_cert(java.lang.Boolean birth_cert) {
		this.birth_cert = birth_cert;
	}

	public java.lang.String getActor() {
		return this.actor;
	}

	public void setActor(java.lang.String actor) {
		this.actor = actor;
	}

	public Party(java.lang.String name, java.lang.String domicile,
			java.lang.Boolean minor, java.lang.String relation,
			java.lang.String docs, java.util.List<java.lang.String> docList,
			java.lang.Boolean idPass, java.lang.Boolean proof_of_residence,
			java.lang.Boolean birth_cert, java.lang.String actor) {
		this.name = name;
		this.domicile = domicile;
		this.minor = minor;
		this.relation = relation;
		this.docs = docs;
		this.docList = docList;
		this.idPass = idPass;
		this.proof_of_residence = proof_of_residence;
		this.birth_cert = birth_cert;
		this.actor = actor;
	}

	

}